using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static SUI.Transfer.Domain.Generator.Consts;

namespace SUI.Transfer.Domain.Generator;

[Generator]
[ExcludeFromCodeCoverage] // This is thoroughly behaviourally tested by the `RecordConsolidationSourceGeneratorTests`, it just isn't picked up by coverage tools.
public class RecordConsolidationSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "SUI.Transfer.Domain.SourceGenerated";
    private const string AttributeName = "GenerateRecordConsolidationAttribute";

    private const string FoundationSourceCode = $$"""
        // <auto-generated/>
        #nullable enable

        using System;
        using System.Diagnostics.CodeAnalysis;
        using System.Text.Json.Serialization;

        namespace {{Namespace}};

        [AttributeUsage(AttributeTargets.Class)]
        {{ExcludeFromCodeCoverageAttributeSource}}
        public class {{AttributeName}}(params Type[] recordTypes) : Attribute
        {
            public Type[] RecordTypes { get; } = recordTypes;
        }

        public interface IProviderRecord<TRecord>
        {
        	string ProviderSystemId { get; }
        	TRecord Record { get; }
        }

        public delegate int FieldRanker(string ProviderSystemId, string RecordName, string PropertyName, string RecordAndPropertyName);

        {{ExcludeFromCodeCoverageAttributeSource}}
        public record ConsolidatedField<TValue>(IReadOnlyCollection<ConsolidatedFieldValue<TValue>> Values)
        {
        	[JsonIgnore]
        	public TValue? Value { get; set; } = Values.Count > 0 ? Values.First().Value : default;
        }

        public record ConsolidatedFieldValue<TValue>(TValue Value, string ProviderSystemId);
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Include the classes that Record Consolidation depends on
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                "RecordConsolidationFoundation.g.cs",
                SourceText.From(FoundationSourceCode, Encoding.UTF8)
            )
        );

        // Filter classes annotated with the [GenerateRecordConsolidation] attribute
        var provider = context
            .SyntaxProvider.CreateSyntaxProvider(
                (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                (syntaxContext, _) => GetClassDeclarationForSourceGen(syntaxContext)
            )
            .Where(t => t.AttributeSyntaxFound != null)
            .Select((t, _) => t.ClassDeclarationSyntax);

        // Generate the applicable Record Consolidation source code
        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(provider.Collect()),
            (productionContext, t) =>
                GenerateRecordConsolidationCode(productionContext, t.Left, t.Right)
        );
    }

    private static (
        ClassDeclarationSyntax ClassDeclarationSyntax,
        AttributeSyntax? AttributeSyntaxFound
    ) GetClassDeclarationForSourceGen(GeneratorSyntaxContext context)
    {
        var classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;

        var attributeSyntaxFound = classDeclarationSyntax
            .AttributeLists.SelectMany(attributeListSyntax => attributeListSyntax.Attributes)
            .Select(attributeSyntax =>
            {
                if (
                    context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol
                    is not IMethodSymbol attributeSymbol
                )
                {
                    return null;
                }

                var attributeName = attributeSymbol.ContainingType.ToDisplayString();

                // Check for the full name of the [GenerateRecordConsolidation] attribute
                return attributeName == $"{Namespace}.{AttributeName}" ? attributeSyntax : null;
            })
            .FirstOrDefault();

        return (classDeclarationSyntax, attributeSyntaxFound);
    }

    private static void GenerateRecordConsolidationCode(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classDeclarations
    )
    {
        // Go through all matched class declarations (i.e. ones with the [GenerateRecordConsolidation] attribute), and generate the consolidation logic
        foreach (var classDeclarationSyntax in classDeclarations)
        {
            var semanticModel = compilation.GetSemanticModel(classDeclarationSyntax.SyntaxTree);

            if (
                semanticModel.GetDeclaredSymbol(classDeclarationSyntax)
                is not INamedTypeSymbol classSymbol
            )
                continue;

            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classDeclarationSyntax.Identifier.Text;

            // Get the record types from the attribute
            var recordConsolidationAttribute = classSymbol
                .GetAttributes()
                .FirstOrDefault(x => x.AttributeClass?.Name == AttributeName);

            var recordTypes = (
                recordConsolidationAttribute
                    ?.ConstructorArguments.First()
                    .Values.Select(t => t)
                    .ToArray() ?? []
            )
                .Select(x => x.Value)
                .OfType<INamedTypeSymbol>()
                .Select(x => new RecordTypeDefinition(x))
                .ToArray();

            // Generate the code blocks
            var namespaces = string.Join(
                NewLine,
                recordTypes.Select(x => $"using {x.Namespace};").Distinct()
            );

            var interfaceMethods = string.Join(
                TwoNewLines,
                recordTypes.Select(x => x.GenerateInterfaceMethodSource()).Distinct()
            );

            var classMethods = string.Join(
                TwoNewLines,
                recordTypes.Select(x => x.GenerateClassMethodSource()).Distinct()
            );

            var consolidatedClasses = string.Join(
                TwoNewLines,
                recordTypes.Select(x => x.GenerateConsolidateClassSource())
            );

            // Build up the final source code
            var code = $$"""
                // <auto-generated/>
                #nullable enable

                using System;
                using System.Collections.Generic;
                using System.Diagnostics.CodeAnalysis;
                using {{Namespace}};
                {{namespaces}}

                namespace {{namespaceName}};

                public interface I{{className}}
                {
                {{interfaceMethods}}
                }

                {{ExcludeFromCodeCoverageAttributeSource}}
                partial class {{className}} : I{{className}}
                {
                {{classMethods}}
                }

                {{consolidatedClasses}}
                """;

            // Add the source code to the compilation
            context.AddSource($"{className}.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }
}
