version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    commit-message:
      prefix: "[gha]-"

  - package-ecosystem: nuget
    directory: "/Apps/Find"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    commit-message:
      prefix: "[nuget][Find]-"
    groups:
      all-version-updates:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directory: "/Apps/StubCustodians"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    commit-message:
      prefix: "[nuget][StubCustodians]-"
    groups:
      all-version-updates:
        patterns:
          - "*"
