version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[gha]-"

  - package-ecosystem: nuget
    directory: "/Find"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[nuget]-"