version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[gha]-"

  # - package-ecosystem: nuget
  #   directory: "/Apps/Matching"
  #   schedule:
  #     interval: "weekly"
  #   commit-message:
  #     prefix: "[nuget][Matching]-"
      
  - package-ecosystem: nuget
    directory: "/Apps/Find"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[nuget][Find]-"
      
  - package-ecosystem: nuget
    directory: "/Apps/SingleView"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[nuget][SingleView]-"
      
  - package-ecosystem: nuget
    directory: "/Apps/StubCustodians"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[nuget][StubCustodians]-"
  
  - package-ecosystem: nuget
    directory: "/Apps/Transfer"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[nuget][Transfer]-"