site_name: Single unique identifier Documentation
docs_dir: Docs/
theme:
  name: material
  custom_dir: resources/tech_docs_template
  logo: logos/govuk-icon-512.png
  favicon: favicons/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.indexes
    - content.code.copy
    - content.action.edit
    - content.action.view
    - toc.integrate # uncomment to merge TOC with navigation bar
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
