@TransferAPI_HostAddress = http://localhost:5062
@SUI = 999-000-1234
@ApiKey = D3v3l0pm3ntK3y

### POST request with api key - Should return 200 (OK) with 
POST {{TransferAPI_HostAddress}}/api/v1/transfer/
X-Api-Key: {{ApiKey}}
Content-Type: application/json

"999-000-1234"


### POST request without api key - Should return 401 (Unauthorized)
POST {{TransferAPI_HostAddress}}/api/v1/transfer/
