@TransferAPI_HostAddress = http://localhost:5062
@SUI = 999-000-1234
@ApiKey = 2f4a84d6d13a7fc2e08c06192c31646c89aefb4b5afd58694695d570

### GET request with api key
GET {{TransferAPI_HostAddress}}/api/v1/transfer/{{SUI}}
X-Api-Key: {{ApiKey}}


### GET request without api key
GET {{TransferAPI_HostAddress}}/api/v1/transfer/{{SUI}}
