//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace SUI.StubCustodians.API.Client
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IStubCustodiansApi
    {
        /// <summary>
        /// Service health check
        /// </summary>
        /// <remarks>
        /// Lightweight health check endpoint to verify that the Find a Record API is responsive. Intended for platform monitoring and load balancer checks.
        /// </remarks>
        /// <returns>Service is healthy.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HealthStatus> StatusAsync();

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Service health check
        /// </summary>
        /// <remarks>
        /// Lightweight health check endpoint to verify that the Find a Record API is responsive. Intended for platform monitoring and load balancer checks.
        /// </remarks>
        /// <returns>Service is healthy.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HealthStatus> StatusAsync(System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Start a Find a Record search
        /// </summary>
        /// <remarks>
        /// Initiates an asynchronous search for existing records associated with the supplied Single Unique Identifier (sui) for a child in social care.
        /// <br/>If an identical active search already exists for the same sui and caller context, the service MAY return that existing job instead of creating a new one.
        /// </remarks>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Search accepted.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SearchJob> StartSearchAsync(string traceparent, string tracestate, StartSearchRequest body);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Start a Find a Record search
        /// </summary>
        /// <remarks>
        /// Initiates an asynchronous search for existing records associated with the supplied Single Unique Identifier (sui) for a child in social care.
        /// <br/>If an identical active search already exists for the same sui and caller context, the service MAY return that existing job instead of creating a new one.
        /// </remarks>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Search accepted.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SearchJob> StartSearchAsync(string traceparent, string tracestate, StartSearchRequest body, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Get search status
        /// </summary>
        /// <remarks>
        /// Retrieve the current status of a Find a Record search job.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Current search job status.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SearchJob> GetSearchAsync(System.Guid jobId, string traceparent, string tracestate);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get search status
        /// </summary>
        /// <remarks>
        /// Retrieve the current status of a Find a Record search job.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Current search job status.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SearchJob> GetSearchAsync(System.Guid jobId, string traceparent, string tracestate, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Cancel a running search
        /// </summary>
        /// <remarks>
        /// Requests cancellation of a running search job. If successful, the job transitions to `cancelled`. Cancellation is idempotent.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Cancel request accepted.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SearchJob> CancelSearchAsync(System.Guid jobId, string traceparent, string tracestate);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Cancel a running search
        /// </summary>
        /// <remarks>
        /// Requests cancellation of a running search job. If successful, the job transitions to `cancelled`. Cancellation is idempotent.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Cancel request accepted.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SearchJob> CancelSearchAsync(System.Guid jobId, string traceparent, string tracestate, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Get search results
        /// </summary>
        /// <remarks>
        /// Returns the results for a Find a Record search job.
        /// <br/>Results MAY be available before the job reaches `completed` status, depending on implementation.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Results for the specified search job.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SearchResults> GetSearchResultsAsync(System.Guid jobId, string traceparent, string tracestate);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get search results
        /// </summary>
        /// <remarks>
        /// Returns the results for a Find a Record search job.
        /// <br/>Results MAY be available before the job reaches `completed` status, depending on implementation.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Results for the specified search job.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SearchResults> GetSearchResultsAsync(System.Guid jobId, string traceparent, string tracestate, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Fetch a record from a participating system
        /// </summary>
        /// <remarks>
        /// Returns a single record wrapped in a standard envelope. The envelope uses a discriminator to select the correct data model based on 'dataType'.
        /// </remarks>
        /// <param name="recordId">Provider-specific identifier for the record.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Record successfully fetched.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<LocalAuthorityChildrenSocialCareCaseEnvelopeV1> FetchRecordAsync(string recordId, string traceparent, string tracestate);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Fetch a record from a participating system
        /// </summary>
        /// <remarks>
        /// Returns a single record wrapped in a standard envelope. The envelope uses a discriminator to select the correct data model based on 'dataType'.
        /// </remarks>
        /// <param name="recordId">Provider-specific identifier for the record.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Record successfully fetched.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<LocalAuthorityChildrenSocialCareCaseEnvelopeV1> FetchRecordAsync(string recordId, string traceparent, string tracestate, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class StubCustodiansApi : IStubCustodiansApi
    {
        private System.Net.Http.HttpClient _httpClient;
        private static System.Lazy<System.Text.Json.JsonSerializerOptions> _settings = new System.Lazy<System.Text.Json.JsonSerializerOptions>(CreateSerializerSettings, true);
        private System.Text.Json.JsonSerializerOptions _instanceSettings;

    #pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public StubCustodiansApi(System.Net.Http.HttpClient httpClient)
    #pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        {
            _httpClient = httpClient;
            Initialize();
        }

        private static System.Text.Json.JsonSerializerOptions CreateSerializerSettings()
        {
            var settings = new System.Text.Json.JsonSerializerOptions();
            UpdateJsonSerializerSettings(settings);
            return settings;
        }

        protected System.Text.Json.JsonSerializerOptions JsonSerializerSettings { get { return _instanceSettings ?? _settings.Value; } }

        static partial void UpdateJsonSerializerSettings(System.Text.Json.JsonSerializerOptions settings);

        partial void Initialize();

        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

        /// <summary>
        /// Service health check
        /// </summary>
        /// <remarks>
        /// Lightweight health check endpoint to verify that the Find a Record API is responsive. Intended for platform monitoring and load balancer checks.
        /// </remarks>
        /// <returns>Service is healthy.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<HealthStatus> StatusAsync()
        {
            return StatusAsync(System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Service health check
        /// </summary>
        /// <remarks>
        /// Lightweight health check endpoint to verify that the Find a Record API is responsive. Intended for platform monitoring and load balancer checks.
        /// </remarks>
        /// <returns>Service is healthy.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<HealthStatus> StatusAsync(System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                
                    // Operation Path: "status"
                    urlBuilder_.Append("status");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<HealthStatus>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Start a Find a Record search
        /// </summary>
        /// <remarks>
        /// Initiates an asynchronous search for existing records associated with the supplied Single Unique Identifier (sui) for a child in social care.
        /// <br/>If an identical active search already exists for the same sui and caller context, the service MAY return that existing job instead of creating a new one.
        /// </remarks>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Search accepted.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<SearchJob> StartSearchAsync(string traceparent, string tracestate, StartSearchRequest body)
        {
            return StartSearchAsync(traceparent, tracestate, body, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Start a Find a Record search
        /// </summary>
        /// <remarks>
        /// Initiates an asynchronous search for existing records associated with the supplied Single Unique Identifier (sui) for a child in social care.
        /// <br/>If an identical active search already exists for the same sui and caller context, the service MAY return that existing job instead of creating a new one.
        /// </remarks>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Search accepted.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<SearchJob> StartSearchAsync(string traceparent, string tracestate, StartSearchRequest body, System.Threading.CancellationToken cancellationToken)
        {
            if (body == null)
                throw new System.ArgumentNullException("body");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (traceparent != null)
                        request_.Headers.TryAddWithoutValidation("traceparent", ConvertToString(traceparent, System.Globalization.CultureInfo.InvariantCulture));

                    if (tracestate != null)
                        request_.Headers.TryAddWithoutValidation("tracestate", ConvertToString(tracestate, System.Globalization.CultureInfo.InvariantCulture));
                    var json_ = System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(body, JsonSerializerSettings);
                    var content_ = new System.Net.Http.ByteArrayContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                
                    // Operation Path: "v1/searches"
                    urlBuilder_.Append("v1/searches");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 202)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<SearchJob>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 400)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Problem>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Problem>("Invalid request (e.g. missing or malformed sui).", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Problem>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Problem>("Error", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Get search status
        /// </summary>
        /// <remarks>
        /// Retrieve the current status of a Find a Record search job.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Current search job status.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<SearchJob> GetSearchAsync(System.Guid jobId, string traceparent, string tracestate)
        {
            return GetSearchAsync(jobId, traceparent, tracestate, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get search status
        /// </summary>
        /// <remarks>
        /// Retrieve the current status of a Find a Record search job.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Current search job status.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<SearchJob> GetSearchAsync(System.Guid jobId, string traceparent, string tracestate, System.Threading.CancellationToken cancellationToken)
        {
            if (jobId == null)
                throw new System.ArgumentNullException("jobId");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (traceparent != null)
                        request_.Headers.TryAddWithoutValidation("traceparent", ConvertToString(traceparent, System.Globalization.CultureInfo.InvariantCulture));

                    if (tracestate != null)
                        request_.Headers.TryAddWithoutValidation("tracestate", ConvertToString(tracestate, System.Globalization.CultureInfo.InvariantCulture));
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                
                    // Operation Path: "v1/searches/{jobId}"
                    urlBuilder_.Append("v1/searches/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(jobId, System.Globalization.CultureInfo.InvariantCulture)));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<SearchJob>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Problem>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Problem>("Search job not found.", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Problem>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Problem>("Error", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Cancel a running search
        /// </summary>
        /// <remarks>
        /// Requests cancellation of a running search job. If successful, the job transitions to `cancelled`. Cancellation is idempotent.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Cancel request accepted.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<SearchJob> CancelSearchAsync(System.Guid jobId, string traceparent, string tracestate)
        {
            return CancelSearchAsync(jobId, traceparent, tracestate, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Cancel a running search
        /// </summary>
        /// <remarks>
        /// Requests cancellation of a running search job. If successful, the job transitions to `cancelled`. Cancellation is idempotent.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Cancel request accepted.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<SearchJob> CancelSearchAsync(System.Guid jobId, string traceparent, string tracestate, System.Threading.CancellationToken cancellationToken)
        {
            if (jobId == null)
                throw new System.ArgumentNullException("jobId");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (traceparent != null)
                        request_.Headers.TryAddWithoutValidation("traceparent", ConvertToString(traceparent, System.Globalization.CultureInfo.InvariantCulture));

                    if (tracestate != null)
                        request_.Headers.TryAddWithoutValidation("tracestate", ConvertToString(tracestate, System.Globalization.CultureInfo.InvariantCulture));
                    request_.Method = new System.Net.Http.HttpMethod("DELETE");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                
                    // Operation Path: "v1/searches/{jobId}"
                    urlBuilder_.Append("v1/searches/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(jobId, System.Globalization.CultureInfo.InvariantCulture)));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 202)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<SearchJob>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Problem>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Problem>("Search job not found.", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Problem>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Problem>("Error", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Get search results
        /// </summary>
        /// <remarks>
        /// Returns the results for a Find a Record search job.
        /// <br/>Results MAY be available before the job reaches `completed` status, depending on implementation.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Results for the specified search job.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<SearchResults> GetSearchResultsAsync(System.Guid jobId, string traceparent, string tracestate)
        {
            return GetSearchResultsAsync(jobId, traceparent, tracestate, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get search results
        /// </summary>
        /// <remarks>
        /// Returns the results for a Find a Record search job.
        /// <br/>Results MAY be available before the job reaches `completed` status, depending on implementation.
        /// </remarks>
        /// <param name="jobId">Identifier of the search job.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Results for the specified search job.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<SearchResults> GetSearchResultsAsync(System.Guid jobId, string traceparent, string tracestate, System.Threading.CancellationToken cancellationToken)
        {
            if (jobId == null)
                throw new System.ArgumentNullException("jobId");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (traceparent != null)
                        request_.Headers.TryAddWithoutValidation("traceparent", ConvertToString(traceparent, System.Globalization.CultureInfo.InvariantCulture));

                    if (tracestate != null)
                        request_.Headers.TryAddWithoutValidation("tracestate", ConvertToString(tracestate, System.Globalization.CultureInfo.InvariantCulture));
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                
                    // Operation Path: "v1/searches/{jobId}/results"
                    urlBuilder_.Append("v1/searches/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(jobId, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append("/results");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<SearchResults>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Problem>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Problem>("Search job not found.", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Problem>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Problem>("Error", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Fetch a record from a participating system
        /// </summary>
        /// <remarks>
        /// Returns a single record wrapped in a standard envelope. The envelope uses a discriminator to select the correct data model based on 'dataType'.
        /// </remarks>
        /// <param name="recordId">Provider-specific identifier for the record.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Record successfully fetched.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<LocalAuthorityChildrenSocialCareCaseEnvelopeV1> FetchRecordAsync(string recordId, string traceparent, string tracestate)
        {
            return FetchRecordAsync(recordId, traceparent, tracestate, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Fetch a record from a participating system
        /// </summary>
        /// <remarks>
        /// Returns a single record wrapped in a standard envelope. The envelope uses a discriminator to select the correct data model based on 'dataType'.
        /// </remarks>
        /// <param name="recordId">Provider-specific identifier for the record.</param>
        /// <param name="traceparent">W3C trace context 'traceparent' header for distributed tracing.</param>
        /// <param name="tracestate">W3C trace context 'tracestate' header for vendor-specific trace data.</param>
        /// <returns>Record successfully fetched.</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<LocalAuthorityChildrenSocialCareCaseEnvelopeV1> FetchRecordAsync(string recordId, string traceparent, string tracestate, System.Threading.CancellationToken cancellationToken)
        {
            if (recordId == null)
                throw new System.ArgumentNullException("recordId");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (traceparent != null)
                        request_.Headers.TryAddWithoutValidation("traceparent", ConvertToString(traceparent, System.Globalization.CultureInfo.InvariantCulture));

                    if (tracestate != null)
                        request_.Headers.TryAddWithoutValidation("tracestate", ConvertToString(tracestate, System.Globalization.CultureInfo.InvariantCulture));
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                
                    // Operation Path: "v1/records/{recordId}"
                    urlBuilder_.Append("v1/records/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(recordId, System.Globalization.CultureInfo.InvariantCulture)));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<LocalAuthorityChildrenSocialCareCaseEnvelopeV1>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Problem>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Problem>("Record not found.", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Problem>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Problem>("Error", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        protected struct ObjectResponseResult<T>
        {
            public ObjectResponseResult(T responseObject, string responseText)
            {
                this.Object = responseObject;
                this.Text = responseText;
            }

            public T Object { get; }

            public string Text { get; }
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<string> ReadAsStringAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
    #if NET5_0_OR_GREATER
            return content.ReadAsStringAsync(cancellationToken);
    #else
            return content.ReadAsStringAsync();
    #endif
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<System.IO.Stream> ReadAsStreamAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
    #if NET5_0_OR_GREATER
            return content.ReadAsStreamAsync(cancellationToken);
    #else
            return content.ReadAsStreamAsync();
    #endif
        }

        public bool ReadResponseAsString { get; set; }

        protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Threading.CancellationToken cancellationToken)
        {
            if (response == null || response.Content == null)
            {
                return new ObjectResponseResult<T>(default(T), string.Empty);
            }

            if (ReadResponseAsString)
            {
                var responseText = await ReadAsStringAsync(response.Content, cancellationToken).ConfigureAwait(false);
                try
                {
                    var typedBody = System.Text.Json.JsonSerializer.Deserialize<T>(responseText, JsonSerializerSettings);
                    return new ObjectResponseResult<T>(typedBody, responseText);
                }
                catch (System.Text.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body string as " + typeof(T).FullName + ".";
                    throw new ApiException(message, (int)response.StatusCode, responseText, headers, exception);
                }
            }
            else
            {
                try
                {
                    using (var responseStream = await ReadAsStreamAsync(response.Content, cancellationToken).ConfigureAwait(false))
                    {
                        var typedBody = await System.Text.Json.JsonSerializer.DeserializeAsync<T>(responseStream, JsonSerializerSettings, cancellationToken).ConfigureAwait(false);
                        return new ObjectResponseResult<T>(typedBody, string.Empty);
                    }
                }
                catch (System.Text.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body stream as " + typeof(T).FullName + ".";
                    throw new ApiException(message, (int)response.StatusCode, string.Empty, headers, exception);
                }
            }
        }

        private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
        {
            if (value == null)
            {
                return "";
            }

            if (value is System.Enum)
            {
                var name = System.Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field_ = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field_ != null)
                    {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field_, typeof(System.Runtime.Serialization.EnumMemberAttribute)) 
                            as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null)
                        {
                            return attribute.Value != null ? attribute.Value : name;
                        }
                    }

                    var converted = System.Convert.ToString(System.Convert.ChangeType(value, System.Enum.GetUnderlyingType(value.GetType()), cultureInfo));
                    return converted == null ? string.Empty : converted;
                }
            }
            else if (value is bool) 
            {
                return System.Convert.ToString((bool)value, cultureInfo).ToLowerInvariant();
            }
            else if (value is byte[])
            {
                return System.Convert.ToBase64String((byte[]) value);
            }
            else if (value is string[])
            {
                return string.Join(",", (string[])value);
            }
            else if (value.GetType().IsArray)
            {
                var valueArray = (System.Array)value;
                var valueTextArray = new string[valueArray.Length];
                for (var i = 0; i < valueArray.Length; i++)
                {
                    valueTextArray[i] = ConvertToString(valueArray.GetValue(i), cultureInfo);
                }
                return string.Join(",", valueTextArray);
            }

            var result = System.Convert.ToString(value, cultureInfo);
            return result == null ? "" : result;
        }
    }

    /// <summary>
    /// RFC 7807 problem details.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Problem
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public System.Uri Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public int Status { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("detail")]
        public string Detail { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("instance")]
        public System.Uri Instance { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Current state of a search job.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum SearchStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"queued")]
        Queued = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"running")]
        Running = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"completed")]
        Completed = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"failed")]
        Failed = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"cancelled")]
        Cancelled = 4,

    }

    /// <summary>
    /// HAL-style link object, extended with HTTP method.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HalLink
    {

        /// <summary>
        /// Target URL.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("href")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Href { get; set; }

        /// <summary>
        /// HTTP method to use when following this link.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("method")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<HalLinkMethod>))]
        public HalLinkMethod Method { get; set; }

    }

    /// <summary>
    /// Request to start a Find a Record search.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class StartSearchRequest
    {

        /// <summary>
        /// Single Unique Identifier (sui) for the child.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("sui")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Sui { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// High-level category (and optional sub-category) of the located record. This is intentionally constrained but can be extended in future versions.
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum RecordType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"local-authority")]
        LocalAuthority = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"local-authority.children-social-care")]
        LocalAuthority_childrenSocialCare = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"education")]
        Education = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"education.attendance")]
        Education_attendance = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"education.exclusion")]
        Education_exclusion = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"health")]
        Health = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"health.mental-health")]
        Health_mentalHealth = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"crime-justice")]
        CrimeJustice = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"housing")]
        Housing = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"housing.homelessness")]
        Housing_homelessness = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"other")]
        Other = 10,

    }

    /// <summary>
    /// Representation of a Find a Record search job.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SearchJob
    {

        /// <summary>
        /// Stable identifier for this search job.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("jobId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid JobId { get; set; }

        /// <summary>
        /// sui used for this search.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("sui")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Sui { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SearchStatus>))]
        public SearchStatus Status { get; set; }

        /// <summary>
        /// When the search was accepted.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// When the search status last changed.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("lastUpdatedAt")]
        public System.DateTimeOffset LastUpdatedAt { get; set; }

        /// <summary>
        /// HAL-style links for this job.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("_links")]
        [System.ComponentModel.DataAnnotations.Required]
        public _links _links { get; set; } = new _links();

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// A single located record endpoint for the requested sui.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SearchResultItem
    {

        /// <summary>
        /// Identifier of the participating system/provider.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("providerSystem")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ProviderSystem { get; set; }

        /// <summary>
        /// Human-readable name for the provider.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("providerName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ProviderName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("recordType")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<RecordType>))]
        public RecordType RecordType { get; set; }

        /// <summary>
        /// URL to use to obtain the record data from the provider.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("recordUrl")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Uri RecordUrl { get; set; }

    }

    /// <summary>
    /// Results for a Find a Record search job.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SearchResults
    {

        /// <summary>
        /// Identifier of the search job.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("jobId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid JobId { get; set; }

        /// <summary>
        /// sui used for this search.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("sui")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Sui { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SearchStatus>))]
        public SearchStatus Status { get; set; }

        /// <summary>
        /// List of systems/records located for the sui.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("items")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<SearchResultItem> Items { get; set; } = new System.Collections.ObjectModel.Collection<SearchResultItem>();

        /// <summary>
        /// HAL-style links for result navigation.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("_links")]
        [System.ComponentModel.DataAnnotations.Required]
        public _links2 _links { get; set; } = new _links2();

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Common fields for all record envelopes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RecordEnvelopeBase
    {

        /// <summary>
        /// Provider-specific identifier for this record.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("recordId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RecordId { get; set; }

        /// <summary>
        /// Identifier of the participating system/provider.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("providerSystem")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ProviderSystem { get; set; }

        /// <summary>
        /// Human-readable name for the provider system.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("providerName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ProviderName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("recordType")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<RecordType>))]
        public RecordType RecordType { get; set; }

        /// <summary>
        /// Logical type of the data payload including version suffix.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dataType")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DataType { get; set; }

        /// <summary>
        /// URI of the JSON Schema that describes the 'data' payload.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("schemaUri")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Uri SchemaUri { get; set; }

    }

    /// <summary>
    /// Example local authority children's social care case payload.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LocalAuthorityChildrenSocialCareCaseDataV1
    {

        [System.Text.Json.Serialization.JsonPropertyName("caseId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CaseId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("childNhsNumber")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ChildNhsNumber { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("startDate")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset StartDate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("endDate")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? EndDate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Status { get; set; }

    }

    /// <summary>
    /// Example education attendance record payload.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EducationAttendanceRecordDataV1
    {

        [System.Text.Json.Serialization.JsonPropertyName("enrolmentId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string EnrolmentId { get; set; }

        /// <summary>
        /// Unique Pupil Number.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("upn")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Upn { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("academicYear")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string AcademicYear { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalSessions")]
        public int TotalSessions { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("authorisedAbsences")]
        public int AuthorisedAbsences { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("unauthorisedAbsences")]
        public int UnauthorisedAbsences { get; set; }

    }

    /// <summary>
    /// Envelope for local-authority.children-social-care.case.v1 records.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LocalAuthorityChildrenSocialCareCaseEnvelopeV1 : RecordEnvelopeBase
    {

        [System.Text.Json.Serialization.JsonPropertyName("recordType")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<RecordType>))]
        public RecordType RecordType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dataType")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<LocalAuthorityChildrenSocialCareCaseEnvelopeV1DataType>))]
        public LocalAuthorityChildrenSocialCareCaseEnvelopeV1DataType DataType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("schemaUri")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<LocalAuthorityChildrenSocialCareCaseEnvelopeV1SchemaUri>))]
        public LocalAuthorityChildrenSocialCareCaseEnvelopeV1SchemaUri SchemaUri { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public LocalAuthorityChildrenSocialCareCaseDataV1 Data { get; set; } = new LocalAuthorityChildrenSocialCareCaseDataV1();

    }

    /// <summary>
    /// Envelope for education.attendance.record.v1 records.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EducationAttendanceRecordEnvelopeV1 : RecordEnvelopeBase
    {

        [System.Text.Json.Serialization.JsonPropertyName("recordType")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<RecordType>))]
        public RecordType RecordType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dataType")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<EducationAttendanceRecordEnvelopeV1DataType>))]
        public EducationAttendanceRecordEnvelopeV1DataType DataType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("schemaUri")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<EducationAttendanceRecordEnvelopeV1SchemaUri>))]
        public EducationAttendanceRecordEnvelopeV1SchemaUri SchemaUri { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public EducationAttendanceRecordDataV1 Data { get; set; } = new EducationAttendanceRecordDataV1();

    }

    /// <summary>
    /// Lightweight health status for the Find a Record service.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HealthStatus
    {

        /// <summary>
        /// Health status indicator.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Status { get; set; }

        /// <summary>
        /// Service identifier.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("service")]
        public string Service { get; set; }

        /// <summary>
        /// Deployed API/service version.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public string Version { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum HalLinkMethod
    {

        [System.Runtime.Serialization.EnumMember(Value = @"GET")]
        GET = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"POST")]
        POST = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"DELETE")]
        DELETE = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class _links
    {

        [System.Text.Json.Serialization.JsonPropertyName("self")]
        [System.ComponentModel.DataAnnotations.Required]
        public HalLink Self { get; set; } = new HalLink();

        [System.Text.Json.Serialization.JsonPropertyName("results")]
        public HalLink Results { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("cancel")]
        public HalLink Cancel { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class _links2
    {

        [System.Text.Json.Serialization.JsonPropertyName("self")]
        [System.ComponentModel.DataAnnotations.Required]
        public HalLink Self { get; set; } = new HalLink();

        [System.Text.Json.Serialization.JsonPropertyName("job")]
        public HalLink Job { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum LocalAuthorityChildrenSocialCareCaseEnvelopeV1DataType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"local-authority.children-social-care.case.v1")]
        LocalAuthority_childrenSocialCare_case_v1 = 0,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum LocalAuthorityChildrenSocialCareCaseEnvelopeV1SchemaUri
    {

        [System.Runtime.Serialization.EnumMember(Value = @"https://schemas.example.gov.uk/sui/local-authority.children-social-care.case.v1.json")]
        Https__schemas_example_gov_uk_sui_localAuthority_childrenSocialCare_case_v1_json = 0,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum EducationAttendanceRecordEnvelopeV1DataType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"education.attendance.record.v1")]
        Education_attendance_record_v1 = 0,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum EducationAttendanceRecordEnvelopeV1SchemaUri
    {

        [System.Runtime.Serialization.EnumMember(Value = @"https://schemas.example.gov.uk/sui/education.attendance.record.v1.json")]
        Https__schemas_example_gov_uk_sui_education_attendance_record_v1_json = 0,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    internal class DateFormatConverter : System.Text.Json.Serialization.JsonConverter<System.DateTimeOffset>
    {
        public override System.DateTimeOffset Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var dateTime = reader.GetString();
            if (dateTime == null)
            {
                throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
            }

            return System.DateTimeOffset.Parse(dateTime);
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTimeOffset value, System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
        }
    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException<TResult> : ApiException
    {
        public TResult Result { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765