using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Attributes;

namespace SUI.Find.FindApi.Models;

public record Problem(
    [property: OpenApiProperty(
        Description = "A URI reference that identifies the problem type. This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type, e.g. using HTML. When this member is not present, its value is assumed to be \"about:blank\"; see RFC 3986."
    )]
        string Type,
    [property: OpenApiProperty(
        Description = "A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization, e.g. using proactive content negotiation; see RFC 9110, Section 12.",
        Nullable = false
    )]
        string Title,
    [property: OpenApiProperty(
        Description = "The HTTP status code generated by the origin server for this occurrence of the problem; see RFC 9110, Section 15.",
        Nullable = false
    )]
        int Status,
    [property: OpenApiProperty(
        Description = "A human-readable explanation specific to this occurrence of the problem.",
        Nullable = false
    )]
        string? Detail,
    [property: OpenApiProperty(
        Description = "A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced."
    )]
        string? Instance
);
