name: Build and Test .NET Projects in /Find

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore ./Find

      - name: Build
        run: dotnet build ./Find --no-restore

      - name: Test
        run: dotnet test ./Find --no-build --logger trx
