version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: 'daily'
    commit-message:
      prefix: "[gha]-"
      
  - package-ecosystem: nuget
    directory: "/Find"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[nuget]-"