name: Publish documentation via GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Docs/**"
      - "mkdocs.yml"
      - "resources/tech_docs_template/**"
      - ".github/workflows/deploy-github-documentation.yaml"

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: folder/requirements.txt
