name: Build and Test "FakeCustodians" Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Apps/FakeCustodians/**"
  pull_request:
    branches:
      - main
    paths:
      - "Apps/FakeCustodians/**"

jobs:
  build-and-test-FakeCustodians:
    name: FakeCustodians - Build Test Dotnet
    uses: ./.github/workflows/build-test-dotnet.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: write
    with:
      directory_name: Apps/FakeCustodians