name: Build and Test "FakeCustodians" Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Apps/FakeCustodians/**"
  pull_request:
    branches:
      - main
    paths:
      - "Apps/FakeCustodians/**"

jobs:
  build-and-test-FakeCustodians:
    name: FakeCustodians - Build Test Dotnet
    uses: ./.github/workflows/build-test-dotnet.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: write
    with:
      directory_name: Apps/FakeCustodians

  generate-openapi:
    name: FakeCustodians - Generate OpenAPI Spec
    runs-on: ubuntu-latest
    needs: build-and-test-FakeCustodians

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Generate OpenAPI JSON
        run: |
          dotnet swagger tofile \
            --output stubCustodians-openapi.json \
            Apps/FakeCustodians/src/SUI.FakeCustodians.Api/bin/Debug/net9.0/SUI.FakeCustodians.Api.dll \
            v1

      - name: Upload Generated OpenAPI Spec
        uses: actions/upload-artifact@v4
        with:
          name: stub-custodians-openapi
          path: stubCustodians-openapi.json
