name: Build and Test Find Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-find:
    name: Find
    uses: ./.github/workflows/build-test-scan-sonar.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: write
    with:
      directory_name: Find