name: Build and Test "Find" Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "./Find/**"
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - "./Find/**"

jobs:
  build-and-test-find:
    name: Find - Build Test Dotnet
    uses: ./.github/workflows/build-test-dotnet.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: write
    with:
      directory_name: Find