name: Build and Test "Matching" Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Apps/Matching/**"
  pull_request:
    branches:
      - main
    paths:
      - "Apps/Matching/**"

jobs:
  build-and-test-matching:
    name: Matching - Build Test Dotnet
    uses: ./.github/workflows/build-test-dotnet.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: write
      packages: read
      actions: write
    with:
      directory_name: Apps/Matching
      project_names: '["SUI.Matching.API"]'
