name: Restart Azure Web App
run-name: >-
  ${{
    format(
      'Restart Azure Web App - {0} in {1}',
      inputs.web_app_descriptor,
      inputs.environment
    )
  }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        default: d01
        type: choice
        options:
          - d01
          - d02
      web_app_descriptor:
        description: Web App to restart
        required: true
        default: custodians01
        type: choice
        options:
          - custodians01
          - uiharness01

  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      web_app_descriptor:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write

jobs:
  restart-web-app:
    runs-on: ${{ fromJSON(vars.RUNNER_LABELS || '["ubuntu-latest"]') }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Load tfvars for ${{ inputs.environment }}
        id: env_config
        uses: ./.github/actions/load-tfvars
        with:
          environment: ${{ inputs.environment }}

      - id: eval
        name: Evaluate Workflow Setup
        env:
          RESOURCE_GROUP_NAME: ${{ format('{0}{1}rg-{2}-{3}', steps.env_config.outputs.subscription_prefix, inputs.environment, steps.env_config.outputs.region_short, steps.env_config.outputs.descriptor) }}
          WEB_APP_NAME: ${{ format('{0}{1}app-{2}-{3}', steps.env_config.outputs.subscription_prefix, inputs.environment, steps.env_config.outputs.region_short, inputs.web_app_descriptor) }}
        run: |
          echo "resource_group_name=$RESOURCE_GROUP_NAME" >> "$GITHUB_OUTPUT"
          echo "web_app_name=$WEB_APP_NAME" >> "$GITHUB_OUTPUT"

          echo "---- Evaluated Workflow Setup: ----"
          echo "RESOURCE_GROUP_NAME: $RESOURCE_GROUP_NAME"
          echo "WEB_APP_NAME: $WEB_APP_NAME"

      - name: Azure login with OIDC for ${{ inputs.environment }}
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Restart Azure Web App
        run: |
          az webapp restart \
            --name ${{ steps.eval.outputs.web_app_name }} \
            --resource-group ${{ steps.eval.outputs.resource_group_name }}
