name: Build and Test "SingleView" Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Apps/SingleView/**"
  pull_request:
    branches:
      - main
    paths:
      - "Apps/SingleView/**"

jobs:
  build-and-test-SingleView:
    name: SingleView - Build Test Dotnet
    uses: ./.github/workflows/build-test-dotnet.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: write
    with:
      directory_name: Apps/SingleView