name: Build, Test and Generate OpenAPI for StubCustodians

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Apps/StubCustodians/**"
  pull_request:
    branches:
      - main
    paths:
      - "Apps/StubCustodians/**"

jobs:
  build-and-test-StubCustodians:
    name: StubCustodians - Build Test Dotnet
    uses: ./.github/workflows/build-test-dotnet.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: write
      packages: read
    with:
      directory_name: Apps/StubCustodians