name: Terraform Core Infrastructure
run-name: Terraform Core - ${{ inputs.environment }} (${{ inputs.apply && 'apply' || 'plan' }})

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        default: d01
        type: choice
        options:
          - d01
      apply:
        description: Apply changes (otherwise plan only)
        required: true
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform core for ${{ inputs.environment }} (${{ inputs.apply && 'apply' || 'plan' }})
    uses: ./.github/workflows/terraform-plan-and-apply.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      apply: ${{ inputs.apply }}
      root: terraform/core
