name: Terraform Formatting

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-format.yml"
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-format.yml"

permissions:
  contents: read

jobs:
  terraform-format:
    name: Terraform format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v4

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive terraform
