name: Build and Test "Transfer" Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Apps/Transfer/**"
  pull_request:
    branches:
      - main
    paths:
      - "Apps/Transfer/**"

jobs:
  build-and-test-Transfer:
    name: Transfer - Build Test Dotnet
    uses: ./.github/workflows/build-test-dotnet.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: write
      packages: read
    with:
      directory_name: Apps/Transfer